#!/bin/bash

export LC_ALL=C.UTF-8
export LANG=C.UTF-8

# process_media -n -s -p /processing/movies -o /movies -m movies -t ${CPU_THREADS}
flock -n /tmp/process_movies.lock -c "process_media -p /processing/movies -o /movies -m movies -t ${CPU_THREADS}" > /proc/1/fd/1 2>/proc/1/fd/2
